# Generated by Django 5.1.6 on 2025-05-30 03:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0004_alter_tematica_materia'),
        ('evaluaciones', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pregunta',
            old_name='texto',
            new_name='imagen',
        ),
        migrations.RemoveField(
            model_name='pregunta',
            name='nivel_dificultad',
        ),
        migrations.RemoveField(
            model_name='pregunta',
            name='tematica',
        ),
        migrations.AddField(
            model_name='actividad',
            name='imagen',
            field=models.TextField(blank=True, default='', null=True),
        ),
        migrations.AddField(
            model_name='actividad',
            name='materia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='cursos.materia'),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='descripcion',
            field=models.TextField(default='Sin descripción', max_length=100),
        ),
        migrations.AddField(
            model_name='pregunta',
            name='pregunta',
            field=models.TextField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='descripcion',
            field=models.TextField(default='Sin descripción', max_length=100),
        ),
        migrations.AlterField(
            model_name='actividad',
            name='tematica',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='cursos.tematica'),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='respuesta_correcta',
            field=models.TextField(default=''),
        ),
    ]
