# Generated by Django 5.1.6 on 2025-05-30 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0002_rename_texto_pregunta_imagen_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pregunta',
            name='descripcion',
        ),
    ]
