# Generated by Django 5.1.6 on 2025-05-30 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0003_remove_pregunta_descripcion'),
    ]

    operations = [
        migrations.AddField(
            model_name='actividad',
            name='estado',
            field=models.TextField(default='Activo'),
        ),
    ]
