# Generated by Django 5.1.6 on 2025-06-02 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evaluaciones', '0004_actividad_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificacion',
            name='notaCualitativa',
            field=models.TextField(default=''),
        ),
    ]
