# Generated by Django 5.1.6 on 2025-03-23 03:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='estudiante',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='contraseña',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='correo_institucional',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='fecha_nacimiento',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='sexo',
        ),
        migrations.RemoveField(
            model_name='responsable',
            name='apellido',
        ),
        migrations.RemoveField(
            model_name='responsable',
            name='telefono',
        ),
    ]
