# Generated by Django 5.1.6 on 2025-03-29 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_remove_materia_docentes_remove_materia_grados_and_more'),
        ('usuarios', '0002_remove_estudiante_apellido_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Administrador',
        ),
        migrations.RemoveField(
            model_name='estudiante',
            name='grado',
        ),
        migrations.RemoveField(
            model_name='docente',
            name='apellido',
        ),
        migrations.DeleteModel(
            name='Grado',
        ),
    ]
