# Generated by Django 5.1.6 on 2025-03-30 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_delete_administrador_remove_estudiante_grado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='responsable',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='usuarios.responsable'),
        ),
    ]
