# Generated by Django 5.1.6 on 2025-02-28 03:54

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('docentes', models.ManyToManyField(related_name='materias', to='usuarios.docente')),
                ('grados', models.ManyToManyField(related_name='materias', to='usuarios.grado')),
            ],
        ),
        migrations.CreateModel(
            name='Tematica',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.TextField(blank=True, null=True)),
                ('grado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tematicas', to='usuarios.grado')),
                ('materia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tematicas', to='cursos.materia')),
            ],
        ),
    ]
