# Generated by Django 5.1.6 on 2025-03-29 03:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materia',
            name='docentes',
        ),
        migrations.RemoveField(
            model_name='materia',
            name='grados',
        ),
        migrations.RemoveField(
            model_name='tematica',
            name='grado',
        ),
    ]
