# Generated by Django 5.1.6 on 2025-03-30 03:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0002_remove_materia_docentes_remove_materia_grados_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='materia',
            name='descripcion',
        ),
    ]
