# Generated by Django 5.1.6 on 2025-03-30 04:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0003_remove_materia_descripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tematica',
            name='materia',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tematicas', to='cursos.materia'),
        ),
    ]
